version: '3.8'
services:
  db:
    image: postgres:12.4
    restart: always
    container_name: db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 60s
      retries: 5
    env_file: .env

    volumes:
      - database:/var/lib/postgresql/data/

  backend:
    container_name: backend
    restart: always
    image: deamanda/prosept:v1
    pull_policy: always
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    env_file:
      - .env
  
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend 
                                                                                                                                             
volumes:
  database: