name: prosept_hakaton_8

on:
  push:
    branches:
      - main

jobs:
  tests:
    name: Testing
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install flake8
    - name: Test with flake8
      run: |
        python -m flake8 --ignore E501,W503,F401
        # тесты